### ISSUE TITLE
Links in telegram won't open

### ISSUE THREAD

**Issue by fcole90** [sergiusens/telegram-snap#13]
If I click a link in Telegram nothing happens. The expected behaviour is to open the default browser (or a new tab on it) and display the page of the link. 

This works correctly in the binary that can be downloaded from the Telegram website.
This feature doesn't work neither confined not unconfined.

Clicking on a link triggers the following warning:

```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.SafeLauncher was not provided by any .service files
```
I think this is a serious limitation over the standard (non snap) app.

**Comment by fcole90** [comment]
With ```sudo apt install snapd-xdg-open``` I solved the issue. Could it be better consider this a known issue and add a note about it in the README?

**Comment by sergiusens** [comment]
this is a general snapd problem which should be fixed and would be fixed
soon from what I recall.

**Comment by ugtar** [comment]
i installed snapd-xdg-open but it didn't solve the issue. the last comments on this ticket are pretty old. is there a current workaround for this issue? I'm on ubuntu 18.04 using telegram edge snap

**Comment by OlegSmelov** [comment]
I've started experiencing this recently, used to work fine previously. Ubuntu 18.04. Installing `snapd-xdg-open` didn't help.

**Comment by sergiusens** [comment]
Please switch to using https://snapcraft.io/telegram-desktop which is supported upstream
