### ISSUE TITLE
Tekegram logo on system tray do not work

### ISSUE THREAD

**Issue by 4815162342lost** [sergiusens/telegram-snap#2]
Dear Sergio,

I have a problem with telegram-sergiusens  0.10.1. Icon on the system tray do not work correctly:
http://imgur.com/a/lbAek

And i do not know about new message, because message counter do not work. 

Could you please fix it?

Best regards, Ilya.

**Comment by sergiusens** [comment]
El domingo, 18 de septiembre de 2016 07h'03:03 ART, 4815162342lost 
notifications@github.com escribió:

> Dear Sergio,
> 
> I have a problem with telegram-sergiusens  0.10.1. Icon on the 
> system tray do not work correctly:
> http://imgur.com/a/lbAek
> 
> And i do not know about new message, because message counter do not work. 
> 
> Could you please fix it?

Did either work on previous versions?

## 

Enviado con Dekko desde mi dispositivo Ubuntu

**Comment by 4815162342lost** [comment]
Same problem was on Lubuntu 16.04. I did not use old version, i think.

**Comment by 4815162342lost** [comment]
My log (maybe it is help to ix the issue):

```
vodka@vodka-PC:~/snap/telegram-sergiusens/5/tdata$ telegram-sergiusens.telegram Qt: Session management error: None of the authentication protocols specified are supported
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.109\" (uid=1000 pid=5211 comm=\"Telegram -workdir /home/vodka/snap/telegram-sergiu\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=2635 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.109\" (uid=1000 pid=5211 comm=\"Telegram -workdir /home/vodka/snap/telegram-sergiu\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=2635 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
"Object path cannot be empty"
"Object path cannot be empty"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2

```

**Comment by 4815162342lost** [comment]
The icon is work when a run app from /snap/telegram-sergiusens/5/tupdates/temp$

**Comment by sergiusens** [comment]
This is really a snapd issue, once [LP: #1600136](https://pad.lv/1600136) is fixed it should work across the board.

**Comment by 3v1n0** [comment]
So... From a deeper look, it seems that the icon here is handled directly by `QDBusTrayIcon` that is shipped with Telegram... It generates the icon with `QDir::tempPath() + QLatin1String("/qt-trayicon-XXXXXX.png");`, thus there's not much to do in order to fix this at ubuntu level.

BTW there's a workaround you can use, and you've to set in the wrapper something like `TMPDIR=$HOME/.cache` (folder must exist before launching the binary). In this way, unity will be able to read that icon. Once `$XDG_RUNTIME_DIR` will be available for the snap (see https://github.com/snapcore/snapd/pull/2281), it could be better to use that one (hoping it's readable for the user).
